### ISSUE TITLE
Doc: introduction: explain purpose

### ISSUE THREAD

**Issue by jwuttke** [michael-hartmann/caps#153]
In the beginning of the user documentation, add one sentence to explain what the Casimir effect is, and one paragraph to explain the purpose of this software.

This software does _not_ "implement" the Casimir effect (as README.md says), _nor_ does it "describe" the effect (as the doc says). It computes certain properties of a certain model. This should be explained in more detail.

**Comment by jwuttke** [comment]
<- https://github.com/openjournals/joss-reviews/issues/2011

**Comment by michael-hartmann** [comment]
We have addressed the issue, see #161. The introduction in the user manual is now longer and contains more information. Instead of putting a lot of references to the introduction of the user manual, we have decided to refer the reader to the JOSS paper. We will add the remark once the JOSS paper got published.
